In [8]:
from numpy import *
a = arange(15).reshape(3,5)
print a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
print a.shape
print a.ndim 
print a.size
print a.dtype
print a.itemsize #all int
print type(a)
b = array([6,7,8])
print type(b)

(3, 5)
2
15
int32
4
<type 'numpy.ndarray'>
<type 'numpy.ndarray'>


In [10]:
#array creation 
c = array([3,4,5]) # c = array(1,2,4,5) wrong way
print type(c) 
d = array([1.2,4.6,7.8])
print type(d)

<type 'numpy.ndarray'>
<type 'numpy.ndarray'>


In [11]:
#array transforms sequences of sequences into two-dimensional arrays,
#sequences of sequences of sequences into three-dimensional arrays, and so on.
e = array( [ (1.5,2,3), (4,5,6) ] )
print e
f = array( [ (1.5,2,3), (4,5,6) , (1,4,8) ])
print f

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]
 [ 1.   4.   8. ]]


In [12]:
#The function zeros creates an array full of zeros, 
#the function ones creates an array full of ones,
#and the function empty creates an array whose initial content is random.
print zeros( (3,4) )
print ones( (2,3,4) )
print empty( (2,3) )

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]


In [13]:
#To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists
print arange( 10, 30, 5 ) # 10 to 30 with lap =5
print arange( 0, 2, 0.3 ) #similar

[10 15 20 25]
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8]


In [14]:
#printing array 
a = arange(6)    # 1d 
print a
b = arange(12).reshape(4,3) #2d
print b
c = arange(24).reshape(2,3,4) #3d
print "3d starts here \n " ,c
print arange(10000).reshape(100,100) # ndimensional 

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
3d starts here 
  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


In [15]:
a = array( [20,30,40,50] )
b = arange( 4 )
c = a-b
print c
b = b**2
print b
a = 10*sin(a)
print a
a<35
array([True, True, False, False], dtype=bool)

[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


array([ True,  True, False, False], dtype=bool)

In [16]:
A = array( [[1,1],[0,1]] )
B = array( [[2,0],[3,4]] )
print A*B #matrix product
print dot(A,B) #dot product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [24]:
C = [1,1]
D = [1,0]
print C*D
print dot(C,D)

TypeError: can't multiply sequence by non-int of type 'list'

In [17]:
#random function
a = random.random((2,3))
print a
print a.sum()
print a.min()
print a.max()

[[ 0.63707266  0.52702663  0.79786506]
 [ 0.84716552  0.56123914  0.60484364]]
3.97521264334
0.527026631438
0.847165515015


In [18]:
# by specifying the axis parameter you can apply an operation along the specified axis of an array:
b = arange(12).reshape(3,4)
print b.sum(axis=0) # sum of each column
print b.min(axis=1) # min of each row
print b.cumsum(axis=1) # cumulative sum along each row

[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [19]:
#Indexing, Slicing
a = arange(10)**3
print a[2] 
print a[2:5]
print a[ : :-1] #revert

8
[ 8 27 64]
[729 512 343 216 125  64  27   8   1   0]


In [20]:
#Shape Manipulation
a = floor(10*random.random((3,4)))
print a.shape
print a.ravel() # flatten the array
a.shape = (6, 2)
print a
a.resize((2,6))
print a
#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
print a.reshape(3,-1)

(3, 4)
[ 6.  3.  5.  1.  5.  3.  6.  8.  4.  4.  4.  5.]
[[ 6.  3.]
 [ 5.  1.]
 [ 5.  3.]
 [ 6.  8.]
 [ 4.  4.]
 [ 4.  5.]]
[[ 6.  3.  5.  1.  5.  3.]
 [ 6.  8.  4.  4.  4.  5.]]
[[ 6.  3.  5.  1.]
 [ 5.  3.  6.  8.]
 [ 4.  4.  4.  5.]]


In [21]:
#Stacking together different arrays
a = floor(10*random.random((2,2)))
b = floor(10*random.random((2,2)))
print vstack((a,b))
print hstack((a,b))
print "h and vstack ends here"
a=array([4.,2.])
b=array([2.,8.])
print a[:,newaxis] 
column_stack((a[:,newaxis],b[:,newaxis]))


[[ 4.  7.]
 [ 7.  3.]
 [ 1.  3.]
 [ 5.  3.]]
[[ 4.  7.  1.  3.]
 [ 7.  3.  5.  3.]]
h and vstack ends here
[[ 4.]
 [ 2.]]


array([[ 4.,  2.],
       [ 2.,  8.]])

In [22]:
#Splitting one array into several smaller ones
a = floor(10*random.random((2,12)))
hsplit(a,3)

[array([[ 9.,  4.,  3.,  5.],
        [ 9.,  5.,  8.,  4.]]), array([[ 6.,  4.,  1.,  9.],
        [ 6.,  5.,  0.,  1.]]), array([[ 9.,  3.,  7.,  8.],
        [ 9.,  8.,  6.,  9.]])]

In [23]:
#linear algebra
from numpy.linalg import *
a = array([[1.0, 2.0], [3.0, 4.0]])
print a.transpose()
print inv(a)
u = eye(2)
print u
print dot (a, u)
print eig(a)

[[ 1.  3.]
 [ 2.  4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  2.]
 [ 3.  4.]]
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
