In [4]:
#Simple perceptron model 
#Author : Himanshu Shukla

In [5]:
from random import choice
from numpy import array,random,dot

In [6]:
#unit step function 
unit_step = lambda x:0 if x<0 else 1
training_data = [ (array([0,0,1]), 0), 
                  (array([0,1,1]), 1), 
                  (array([1,0,1]), 1), 
                  (array([1,1,1]), 1), ] #A||B third value is dummy value (for bias threshold) 


In [12]:
w = random.rand(3) #three random numbers between 0 and 1 as the initial weights:
print w
errors = []  #this list is to store errors only (useful if we want to plot the errors)
eta = 0.2 #learning rate
n = 100 #no of iterations 

[ 0.34287212  0.82358246  0.49557905]


In [15]:
#we try to reduce the error magnitude to zero.
#First we get a random input set from the training data. Then we calculate the dot product 
#of the input and weight vectors. The result is compared with expected value. If the expected value is bigger, 
#we need to increase the weights, if it's smaller, we need to decrease them. 
#This correction factor is calculated in the last line, where the error is multiplied with the learning rate (eta) 
#and the input vector (x). It is then added to the weights vector, in order to improve the results in the next iteration.
for i in xrange(n): 
    x, expected = choice(training_data) 
    print "x and expected are",x,expected
    result = dot(w, x) 
    print "result is ",result 
    error = expected - unit_step(result) 
    print "error is ",error 
    errors.append(error) 
    w += eta * error * x
    print "w is",w

x and expected are [0 0 1] 0
result is  0.495579045332
error is  -1
w is [ 0.34287212  0.82358246  0.29557905]
x and expected are [1 1 1] 1
result is  1.46203362106
error is  0
w is [ 0.34287212  0.82358246  0.29557905]
x and expected are [0 0 1] 0
result is  0.295579045332
error is  -1
w is [ 0.34287212  0.82358246  0.09557905]
x and expected are [0 0 1] 0
result is  0.0955790453323
error is  -1
w is [ 0.34287212  0.82358246 -0.10442095]
x and expected are [0 0 1] 0
result is  -0.104420954668
error is  0
w is [ 0.34287212  0.82358246 -0.10442095]
x and expected are [0 0 1] 0
result is  -0.104420954668
error is  0
w is [ 0.34287212  0.82358246 -0.10442095]
x and expected are [0 1 1] 1
result is  0.719161505678
error is  0
w is [ 0.34287212  0.82358246 -0.10442095]
x and expected are [0 0 1] 0
result is  -0.104420954668
error is  0
w is [ 0.34287212  0.82358246 -0.10442095]
x and expected are [0 1 1] 1
result is  0.719161505678
error is  0
w is [ 0.34287212  0.82358246 -0.10442095]
x an

In [9]:
for x, _ in training_data: 
    result = dot(x, w) 
    print("{}: {} -> {}".format(x[:2], result, unit_step(result)))

[0 0]: -0.0992945078765 -> 0
[0 1]: 0.781339262955 -> 1
[1 0]: 0.535105346287 -> 1
[1 1]: 1.41573911712 -> 1
